name: SKIF_FTP

on:
  schedule:
    # Будние дни: запуск в 09:30 UTC+5 (04:30 UTC)
    - cron: '30 4 * * 1-5'
    # Выходные дни: запуск в 18:00 UTC+5 (13:00 UTC)
    - cron: '0 13 * * 6,0'

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install selenium webdriver-manager pandas openpyxl

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        DRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Create temp download directory
      run: mkdir -p ./downloads  # Сохранение внутри репозитория

    - name: Run Python script
      env:
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        SITE_EMAIL: ${{ secrets.SITE_EMAIL }}
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        SITE_URL: ${{ secrets.SITE_URL }}
        FTP_URL: ${{ secrets.FTP_URL }}
      run: python3 skif.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./downloads/*  # Добавить все скачанные файлы
        git commit -m "Add downloaded files" || echo "No changes to commit"
        git push origin main  # Замените 'main' на вашу ветку, если она отличается
